os: linux
branches:
  only:
    - master
language: node_js
node_js:
  - 14

git:
  depth: 3
  quiet: true
  submodules: false

cache:
  directories:
    - vuejs/.yarn/cache
    - vuejs/node_modules

install: bash ./scripts/install.sh

deploy:
  - provider: script
    skip_cleanup: true
    script:
      - bash ./scripts/prod-build.sh
      - bash ./scripts/prod-deploy.sh
      - bash ./scripts/prod-after-deploy.sh
      - bash ./scripts/prod-release.sh
    on:
      branch: master

  - provider: script
    skip_cleanup: true
    script:
      - bash ./scripts/dev-build.sh
      - bash ./scripts/dev-deploy.sh
      - bash ./scripts/dev-after-deploy.sh
      - bash ./scripts/dev-release.sh
    on:
      branch: dev
