os: linux
branches:
  only:
    - master
    - dev
language: node_js
node_js:
  - 14

git:
  depth: 3
  quiet: true
  submodules: false

cache:
  directories:
    - vuejs/.yarn/cache
    - vuejs/node_modules

install: bash ./scripts/install.sh

script: bash ./scripts/before-build.sh

deploy:
  - provider: script
    skip_cleanup: true
    script: bash ./scripts/prod-deploy.sh
    on:
      branch: master

  - provider: script
    skip_cleanup: true
    script: bash ./scripts/dev-deploy.sh
    on:
      branch: dev
