os: linux
language: node_js
node_js:
  - 14

install: bash ./scripts/install.sh

script: bash ./scripts/build.sh

deploy:
  - provider: script
    skip_cleanup: true
    script: bash ./scripts/deploy.sh production
    on:
      branch: master

  - provider: script
    skip_cleanup: true
    script: bash ./scripts/deploy.sh dev
    on:
      branch: dev
