language: node_js

node_js:
  - 14

install:
  - chmod u+x ./scripts/install.sh
  - bash ./scripts/install.sh

script:
  - chmod u+x ./scripts/build.sh
  - bash ./scripts/build.sh

deploy:
  - provider: script
    script: bash ./scripts/deploy.sh production
    on:
      branch: master

  - provider: script
    script: bash ./scripts/deploy.sh dev
    on:
      branch: dev
