language: node_js

node_js:
  - 14

install:
  - chmod u+x ./scripts/install.sh
  - bash ./scripts/install.sh

script:
  - chmod u+x ./scripts/build.sh
  - bash ./scripts/build.sh

deploy:
  - provider: pages
    local-dir: ./vuejs/outputs
    target-branch: build
    email: tksudharshan@gmail.com
    name: tks18
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    on:
      branch: master

  - provider: pages
    local-dir: ./vuejs/outputs
    target-branch: dev-build
    email: tksudharshan@gmail.com
    name: tks18
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    on:
      branch: dev
